### ISSUE TITLE
*API Call should look like...*

### ISSUE THREAD

**Issue by jasonfesta** [de-ai/playground.designengine.ai#38]
1. Loads main page default to "Pages": https://getobit.com/domain/hash/project-name
2. Loads entire section: https://getobit.com/domain/hash/project-name/section-name
3. Loads exact element: https://getobit.com/domain/hash/project-name/type-name/element-name
4. Loads exact element event: https://getobit.com/domain/hash/project-name/type-name/element-name/event-name
5. Loads exact element event: https://getobit.com/domain/hash/project-name/type-name/element-name/event-name/mode-type

**Comment by mtholcombe** [comment]
/app/:teamSlug([a-z\-]+)/:projectSlug([a-z\-]+)?/:playgroundID([0-9]+)?/:componentsSlug([A-Za-z\-]+)?/:componentID([0-9]+)?/:commentID([0-9]+)?

https://pairurl.com/app/team-name/project-name/1/buttons/5/77
