### ISSUE TITLE
Sign Up Routing

### ISSUE THREAD

**Issue by jasonfesta** [de-ai/playground.designengine.ai#508]
app.pairurl.com/signup & app.pairurl.com/login should route user accordingly when logged out.

Full day
 - [ ] New subdomain + SSL
 - [ ] Verify Invite record gets written to db
 - [ ] Send email via sendgrid with invite id
 - [ ] Invite url in email redirects to app, shows register modal
 - [ ] User signs up with email + sends invite id
 - [ ] Api marks invite as accepted, joins to team
 - [ ] App redirects to ask page

**Comment by mtholcombe** [comment]
Full day's work.

1. Verify Invite record gets written to db
2. Send email via sendgrid with invite id 
3. Invite url in email redirects to app, shows register modal
4. User signs up with email + sends invite id
5. Api marks invite as accepted, joins to team
6. App redirects to ask page
