### ISSUE TITLE
API: adjust join team call to support multiple teams

### ISSUE THREAD

**Issue by jasonfesta** [de-ai/playground.designengine.ai#555]

**Comment by mtholcombe** [comment]
- [ ] Check for org based on email domain
- [ ] Create new org or add user to existing
- [ ] Create new team or add user to existing
- [ ] Add to `team_members` with `creator,owner` role if created / else role is `member`
- [ ] Add to `org_teams` if new team
- [ ] Check org member total for pricing plan
- [ ] Drop `users_playgrounds` and just go of `teams_builds`
